// SYNTAX TEST "Packages/Lark/Lark.sublime-syntax"

?start: value
//<- keyword.operator.lark
//^^^^ entity.name.function.constructor.lark
//    ^ keyword.operator.assignment.lark

?value: object
      | array
      | string
      | SIGNED_NUMBER      -> number
      | "true"             -> true
      | "false"            -> false
      | "null"             -> null

array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)*] "}"
pair   : string ":" value

string : ESCAPED_STRING

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS

%ignore WS